---
name: Business Input
description: Submit the details for a blog idea to capture as much info as
  possible, at the time of ideation.
title: "Things for the business owner: "
labels:
  - business owner
body:
  - type: input
    id: business-owner
    attributes:
      label: Data sets
      description: >
        Hello legal
        Your assistance is required to complete the data impact assessment for dmf-poc. Please provide the information requested after the summary of the current state of the assessment. This issue is related to pull request #49

        Solution description: IBM Research trained models are Enterprise-level English-language models trained with large volumes of data that has gone intensive pre-processing and careful analysis. The Granite Base (13B) V1.0 has been trained using the 0.3 version of the IBM Data Pile, which consists of well over 1T tokens.
        dmf-poc reads the following data sets:
          ArXiv from
          DeepMind Mathematics from
          Project Gutenberg from
          PubMed Central from
          US Patents from
          GitHub Clean from
          Free Law from
          SEC Filing from
          CommonCrawl CC-MAIN-2022-33 from
            which contains PI
          CommonCrawl CC-MAIN-2022-40 from
            which contains PI
          CommonCrawl CC-MAIN-2022-49 from
            which contains PI
          Hacker News from
          Open Web Text from
          Webhose from
          Wikimedia from

    validations:
      required: false
  - type: textboxes
    id: legalBasis
    attributes:
      label: Legal Basis
      description:  "solution.processingInfo.legalBasis: Choose 1"
      options:
        - label: "Legal obligation: the processing is necessary for IBM to comply with the law <!--solution.processingInfo.legalBasis-->"
        - label: "Legal obligation: the processing is necessary for IBM to comply with the law <!--solution.processingInfo.legalBasis-->"
        - label: "Contract: the processing is necessary to fulfill a contract between IBM and the data subject <!--solution.processingInfo.legalBasis-->"
        - label: "Legitimate interests: the processing is necessary for IBM's (or a third-party's) legitimate interests and those legitimate interests are not overridden by a reason to protect the data subject's personal information from the processing <!--solution.processingInfo.legalBasis-->"
        - label: "Express Consent: the data subject has given clear consent for IBM to process their personal data for a specific purpose <!--solution.processingInfo.legalBasis-->"
  - type: textboxes
    id: legalBasis
    attributes:
      label: Risk
      description:  "solution.processingInfo.consentLink: Choose 1" 
      options:
        - label: High <!--overallRisk-->
        - label: Medium <!--overallRisk-->
        - label: Low <!--overallRisk-->
  - type: input
    id: sensitivity
    attributes:
      label: Data sensitivity
      description: >
        replace $ by relevant values in the following template:

        datasets.1.metadata.dataItems: sensitivity of column $ classified as $ is $
        e.g., datasets.1.metadata.dataItems: sensitivity of column ACCOUNT classified as FINANCE is PI
    validations:
      required: false
